### ISSUE TITLE
Show change log

### ISSUE THREAD

**Issue by Fwaith** [Fwaith/A-Text-Editor#9]

**Comment by BenIskauskas** [comment]
**Idea for implementation for change log:**

Given the prompt:  _Display the sequence of operations performed on all files created by your program, including the number of lines following each operation._

This could be a good idea if we want to keep track of the changes for each individual file (it would be easier if we just keep track of all changes, but the wording of the prompt is unclear imo).

Inside the main file we could declare a 2D array "change_log". 

The name of the file would be the first element in each array, then following it would be any changes made, eg: [0][0] would be "file1" followed by [0][1] "'file1 created successfully\n" and so on. 

Using the file commands for example, since they are currently "void", we could change them to return a string depending on how they execute, then inside the while running loop in the main function we append whatever statement was returned. We already have print statements which could be returned and appended into the array.

To show the change log the user would enter the name of the file they want to view, then we iterate over the array and to find the given file.

Hope this makes sense, just an idea :)
